vc_mem: Fix if directive with CONFIG_DEBUG_FS
When CONFIG_DEBUG_FS is disabled, clang warns:

drivers/char/broadcom/vc_mem.c:376:5: error: 'CONFIG_DEBUG_FS' is not
defined, evaluates to 0 [-Werror,-Wundef]

Fixes: 84b4fbbb194dd ("vc_mem: Add vc_mem driver for querying firmware memory addresses")
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>