staging: vchiq_arm: Add a cast to uintptr_t in vchiq_prepare_bulk_data
Clang warns:

drivers/staging/vc04_services/interface/vchiq_arm/vchiq_2835_arm.c:296:15:
error: cast to 'void *' from smaller integer type 'unsigned int'
[-Werror,-Wint-to-void-pointer-cast]
        bulk->data = (void *)VC_SAFE(pagelistinfo->dma_addr);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Fixes: f30d552e148e ("vchiq: Add 36-bit address support")
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>