rtl8192cu: rtw_android: Fix several cast warnings
Clang warns a bunch:

drivers/net/wireless/realtek/rtl8192cu/os_dep/linux/rtw_android.c:377:30:
error: incompatible integer to pointer conversion passing
'compat_uptr_t' (aka 'unsigned int') to parameter of type 'const void *'
[-Werror,-Wint-conversion]
drivers/net/wireless/realtek/rtl8192cu/os_dep/linux/rtw_android.c:382:30:
error: cast to 'void *' from smaller integer type 'compat_uptr_t' (aka
'unsigned int') [-Werror,-Wint-to-void-pointer-cast]
drivers/net/wireless/realtek/rtl8192cu/os_dep/linux/rtw_android.c:568:61:
error: incompatible integer to pointer conversion passing
'compat_uptr_t' (aka 'unsigned int') to parameter of type 'char *'
[-Werror,-Wint-conversion]
drivers/net/wireless/realtek/rtl8192cu/os_dep/linux/rtw_android.c:588:62:
error: incompatible integer to pointer conversion passing
'compat_uptr_t' (aka 'unsigned int') to parameter of type 'char *'
[-Werror,-Wint-conversion]
drivers/net/wireless/realtek/rtl8192cu/os_dep/linux/rtw_android.c:612:20:
error: cast to 'void *' from smaller integer type 'compat_uptr_t' (aka
'unsigned int') [-Werror,-Wint-to-void-pointer-cast]

I do not really see the point to CONFIG_COMPAT...

Make this structure match rtl8188eu, remove the void * casts, and remove
the access_ok check before copy_from_user, because it happens
automatically there.

Not that it really matters, we aren't running this on Android :)

Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>