media: i2c: ov9281: Fix uninitialized warning
Clang warns:

drivers/media/i2c/ov9281.c:912:6: error: variable 'id_msb' is used
uninitialized whenever 'if' condition is false
[-Werror,-Wsometimes-uninitialized]
        if (!ret)
            ^~~~
drivers/media/i2c/ov9281.c:915:9: note: uninitialized use occurs here
        id |= (id_msb << 8);
               ^~~~~~
drivers/media/i2c/ov9281.c:912:2: note: remove the 'if' if its condition
is always true
        if (!ret)
        ^~~~~~~~~
drivers/media/i2c/ov9281.c:907:20: note: initialize the variable
'id_msb' to silence this warning
        u32 id = 0, id_msb;
                          ^
                           = 0
1 error generated.

Fixes: 55da9a01fc1c ("media: i2c: ov9281: Read chip ID via 2 reads")
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>